# Generated by Django 6.0.5 on 2026-05-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('ml', 'millilitres'), ('ea', 'each')], default='g', max_length=8)),
                ('minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimum (par level)')),
                ('weekly_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_by', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stocktake')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('stocktake', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pack_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
            ],
            options={
                'ordering': ['product', 'pack_price'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
