# Generated by Django 5.1.15 on 2026-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_department_product_department_stocktake_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockline',
            name='carried_over',
            field=models.BooleanField(default=False),
        ),
    ]
