# Generated by Django 5.1.15 on 2026-05-21 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockline_carried_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='stock.department')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=50)),
                ('use_by', models.DateField(blank=True, null=True)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='stock.product')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='stock.delivery')),
            ],
            options={
                'ordering': ['use_by', '-created'],
            },
        ),
    ]
