# Generated by Django 5.1.15 on 2026-05-22 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_adjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierprice',
            options={'ordering': ['product', '-effective_date', '-id']},
        ),
        # The (product, supplier) unique constraint is gone in code so the
        # SupplierPrice table can hold dated history rows. Use a state-only
        # alteration: some existing dev databases never actually carried the
        # composite UNIQUE index (SQLite rebuilds dropped it at some point),
        # so the default schema editor would error trying to drop a
        # non-existent constraint. No production data is affected; existing
        # rows simply remain valid as the first history entry per supplier.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='supplierprice',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
