# Generated by Django 5.1.15 on 2026-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_supplierprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dry_goods', 'Dry Goods'), ('dairy_eggs', 'Dairy & Eggs'), ('frozen_goods', 'Frozen Goods'), ('fruit_veg', 'Fruit & Veg'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20),
        ),
    ]
