# Generated by Django 5.1.15 on 2026-05-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_ingredientallergen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('finished_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('deposit_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cook_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('method_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='stock.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_g', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='stock.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.recipe')),
                ('sub_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_lines', to='stock.recipe')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('sub_recipe__isnull', True)), models.Q(('ingredient__isnull', True), ('sub_recipe__isnull', False)), _connector='OR'), name='recipeline_xor_ingredient_subrecipe')],
            },
        ),
    ]
