# Generated by Django 5.1.15 on 2026-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_recipe_recipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='role',
            field=models.CharField(choices=[('final_product', 'Final product'), ('component', 'Component')], default='final_product', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='role_is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
