# Generated by Django 5.1.15 on 2026-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_sold_as_product_replaces_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dry_goods', 'Dry Goods'), ('dairy_eggs', 'Dairy & Eggs'), ('frozen_goods', 'Frozen Goods'), ('fruit_veg', 'Fruit & Veg'), ('packaging', 'Packaging'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20),
        ),
    ]
