# Generated by Django 5.1.15 on 2026-05-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_quantity', models.CharField(blank=True, max_length=64)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('packaging', models.ForeignKey(help_text='A Product in the Packaging category (NPD-P*).', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipe_packaging', to='stock.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_links', to='stock.recipe')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'unique_together': {('recipe', 'packaging')},
            },
        ),
    ]
