# Generated by Django 5.1.15 on 2026-05-23 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_recipepackaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('ordered_by', models.CharField(blank=True, max_length=120)),
                ('customer_type', models.CharField(choices=[('internal', 'Internal'), ('wholesale', 'Wholesale')], default='internal', max_length=12)),
                ('is_type_manual', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stock.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
