# Generated by Django 5.1.15 on 2026-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
    ]
