# Generated by Django 5.1.15 on 2026-05-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_customer_is_manual_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('suppressed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_basic_manual',
            field=models.BooleanField(default=False),
        ),
    ]
