# Generated by Django 5.1.15 on 2026-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_suppressedrecipe_recipe_is_basic_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
