# Generated by Django 5.1.15 on 2026-05-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_recipe_archived_recipe_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sage_number', models.CharField(blank=True, max_length=40)),
                ('pack_size', models.CharField(blank=True, max_length=40)),
                ('link_source', models.CharField(choices=[('sage', 'Sage No. match'), ('name', 'Exact name match'), ('manual', 'Manually linked'), ('none', 'Not linked')], default='none', max_length=10)),
                ('link_confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='stock.department')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_products', to='stock.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
