# Generated by Django 5.1.15 on 2026-05-23 20:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_orderline_snapshot(apps, schema_editor):
    """Copy the linked SaleProduct's current name + price onto each
    existing OrderLine. One-time best-effort — for lines created
    before the snapshot fields existed, the current catalogue values
    are the only thing we have. Lines created from now on snapshot
    at write time via OrderLine.save()."""
    OrderLine = apps.get_model("stock", "OrderLine")
    for line in OrderLine.objects.select_related("sale_product").all():
        sp = line.sale_product
        if sp is None:
            continue
        changed = False
        if not line.product_name:
            line.product_name = sp.name or ""
            changed = True
        if line.unit_price is None and sp.price is not None:
            line.unit_price = sp.price
            changed = True
        if changed:
            line.save(update_fields=["product_name", "unit_price"])


def noop_reverse(apps, schema_editor):
    # Nothing to undo on the data side — dropping the columns happens
    # via the schema operations being reversed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_order_orderline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product_name',
            field=models.CharField(blank=True, help_text='Name as it appeared on the order — independent of any later renames or removals in the catalogue.', max_length=200),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price charged on this line — independent of any later catalogue price changes.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sale_product',
            field=models.ForeignKey(blank=True, help_text='Current catalogue product, if one matches; null for historical lines whose product is no longer sold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='stock.saleproduct'),
        ),
        migrations.RunPython(backfill_orderline_snapshot, noop_reverse),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(condition=models.Q(('sale_product__isnull', False)), fields=('order', 'sale_product'), name='orderline_unique_order_saleproduct_when_linked'),
        ),
    ]
