# Generated by Django 5.1.15 on 2026-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_orderline_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the imported week.', unique=True)),
                ('import_version', models.PositiveIntegerField(help_text='Value of HISTORICAL_IMPORT_VERSION at import time; older stamps trigger a re-import on the next deploy.')),
                ('file_path', models.CharField(blank=True, help_text="Source workbook for the most recent import — pure audit; the gate doesn't consult this field.", max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
