# Generated by Django 5.1.15 on 2026-05-24 09:45

from django.db import migrations, models


# Exactly these two names flip to is_internal=True. Anything else (Estate
# outlets, wholesale accounts) stays False — they're all real revenue.
# Matched case-insensitively against Customer.name so the migration is
# resilient to casing drift on the order sheet ("Bakery Internal Use"
# vs "BAKERY INTERNAL USE"). New internal customers added later still
# need to be flipped by hand on the customer edit page or in admin.
INTERNAL_NAMES = ("BAKERY INTERNAL USE", "BAKERY WASTAGE")


def flag_internal_customers(apps, schema_editor):
    Customer = apps.get_model("stock", "Customer")
    for name in INTERNAL_NAMES:
        Customer.objects.filter(name__iexact=name).update(is_internal=True)


def unflag_internal_customers(apps, schema_editor):
    Customer = apps.get_model("stock", "Customer")
    Customer.objects.filter(name__in=INTERNAL_NAMES).update(is_internal=False)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_historicalimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_internal',
            field=models.BooleanField(default=False, help_text="Internal use / non-revenue (bakery's own consumption or wastage). Excluded from the Week total but still listed."),
        ),
        migrations.RunPython(flag_internal_customers, unflag_internal_customers),
    ]
