from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="stock/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("home/", views.home, name="home"),
    path("stock/", views.stock_home, name="stock_home"),
    path("recipes/", views.recipes_home, name="recipes"),
    path("recipes/upload/", views.recipe_upload, name="recipe_upload"),
    path("recipes/upload/preview/", views.recipe_upload_preview, name="recipe_upload_preview"),
    path("recipes/bulk-delete/", views.recipe_bulk_delete, name="recipe_bulk_delete"),
    path("recipes/<int:pk>/", views.recipe_detail, name="recipe_detail"),
    path("recipes/<int:pk>/edit/", views.recipe_edit, name="recipe_edit"),
    path("recipes/<int:pk>/delete/", views.recipe_delete, name="recipe_delete"),
    path("recipes/<int:pk>/sold/", views.recipe_set_sold, name="recipe_set_sold"),
    path("production/", views.production_home, name="production"),
    path("rota/", views.rota_home, name="rota"),
    path("notes/", views.notes_home, name="notes"),
    path("profile/", views.profile, name="profile"),
    path("switch/<int:pk>/", views.switch_department, name="switch_department"),
    path("suppliers/", views.suppliers, name="suppliers"),
    path("suppliers/<int:pk>/delete/", views.supplier_delete, name="supplier_delete"),
    path("products/", views.products, name="products"),
    path("packaging/", views.packaging, name="packaging"),
    path("products/<int:pk>/", views.product_detail, name="product_detail"),
    path("products/<int:pk>/delete/", views.product_delete, name="product_delete"),
    path("price/<int:price_id>/delete/", views.price_delete, name="price_delete"),
    path("reorder/", views.reorder, name="reorder"),
    path("reorder/csv/", views.reorder_csv, name="reorder_csv"),
    path("stocktakes/", views.stocktakes, name="stocktakes"),
    path("stocktakes/<int:pk>/count/", views.count, name="count"),
    path("stocktakes/<int:pk>/csv/", views.stocktake_csv, name="stocktake_csv"),
    path("count/line/<int:line_id>/", views.save_count, name="save_count"),
    path("deliveries/", views.deliveries, name="deliveries"),
    path("deliveries/new/", views.delivery_new, name="delivery_new"),
    path("deliveries/scan/", views.delivery_scan, name="delivery_scan"),
    path("deliveries/<int:pk>/", views.delivery_detail, name="delivery_detail"),
    path("adjustments/", views.adjustments, name="adjustments"),
    path("customers/", views.customers_internal, name="customers"),
    path("customers/wholesale/", views.customers_wholesale, name="customers_wholesale"),
    path("customers/new/", views.customer_new, name="customer_new"),
    path("customers/<int:pk>/", views.customer_detail, name="customer_detail"),
    path("customers/<int:pk>/edit/", views.customer_edit, name="customer_edit"),
    path("customers/<int:pk>/delete/", views.customer_delete, name="customer_delete"),
    path("customers/<int:pk>/type/", views.customer_set_type, name="customer_set_type"),
]
